### ISSUE TITLE
Bug: Spacing issue in rendering

### ISSUE THREAD

**Issue by henil** [mosaic-org/mosaic#93]
Expected:
![1607611087_Dec10_20:08:07](https://user-images.githubusercontent.com/71698300/101786048-794e4980-3b23-11eb-845e-4c42e8a20fc5.png)

Actual:
![1607611054_Dec10_20:07:34](https://user-images.githubusercontent.com/71698300/101785968-620f5c00-3b23-11eb-8e61-e03e6c7d0d44.png)

Log:
[mosaic-3.log](https://github.com/mosaic-org/mosaic/files/5673490/mosaic-3.log)

`cat`ing the log file outside of mosaic gives expected output, so the bug seems to be in the rendering.

Also, this issue doesn't happen with normal files containing tabs/spaces.

This is the relevant part of the greeting prompt.
```fish
echo -ne (\
        df -l -h | grep -E 'dev/(xvda|sd|mapper)' | \
        awk '{printf "\\\\t%s\\\\t%4s / %4s  %s\\\\n\n", $6, $3, $2, $5}' | \
        sed -e 's/^\(.*\([8][5-9]\|[9][0-9]\)%.*\)$/\\\\e[0;31m\1\\\\e[0m/' -e 's/^\(.*\([7][5-9]\|[8][0-4]\)%.*\)$/\\\\e[0;33m\1\\\\e[0m/' | \
        paste -sd ''\
    )
```
NOTE: Pasting this directly to mosaic is also causing a panic, so for now, we need to create a shell script and run it with fish to test.

**Comment by imsnif** [comment]
@henil - I merged a fix for this to main. For me your file looks properly with `cat` - can you please confirm?

**Comment by henil** [comment]
@imsnif Thanks that fixes the issue.

>  For me your file looks properly with cat - can you please confirm?

Yes, they look the same(with and without mosaic) now :)

But pasting this code (not even running, just pasting) directly into mosaic causes a panic for me. At first I thought it was due to tab not being handled but its still happening.
```fish
echo -ne (\
        df -l -h | grep -E 'dev/(xvda|sd|mapper)' | \
        awk '{printf "\\\\t%s\\\\t%4s / %4s  %s\\\\n\n", $6, $3, $2, $5}' | \
        sed -e 's/^\(.*\([8][5-9]\|[9][0-9]\)%.*\)$/\\\\e[0;31m\1\\\\e[0m/' -e 's/^\(.*\([7][5-9]\|[8][0-4]\)%.*\)$/\\\\e[0;33m\1\\\\e[0m/' | \
        paste -sd ''\
    )
```
This is the error
> Error: thread 'screen' panicked at 'swap_remove index (is 36) should be < len (is 1)': library/alloc/src/vec.rs:979

Should this go in a new issue?

**Comment by imsnif** [comment]
Yes, please open a new issue. Otherwise it will be hard (especially for others) to follow.
